CREATE TABLE IF NOT EXISTS T_BBS_M (
    ID SERIAL NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENTS TEXT NOT NULL,
    READ_CNT INTEGER NOT NULL DEFAULT 0 ,
    CRT_ID VARCHAR(20),
    CRT_DT TIMESTAMP,
    MDF_ID VARCHAR(20),
    MDF_DT TIMESTAMP,
    CONSTRAINT PK_BBS_M PRIMARY KEY (ID)
);

COMMENT on column T_BBS_M.ID is 'ID';
COMMENT on column T_BBS_M.TITLE is '제목';
COMMENT on column T_BBS_M.CONTENTS is '내용';
COMMENT on column T_BBS_M.READ_CNT is '조회수';
COMMENT on column T_BBS_M.CRT_ID is '생성자ID';
COMMENT on column T_BBS_M.CRT_DT is '생성일시';
COMMENT on column T_BBS_M.MDF_ID is '수정자ID';
COMMENT on column T_BBS_M.MDF_DT is '수정일시';
