##############################################################
# Spring Database 처리
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    driver-class-name: org.postgresql.Driver
    username: hermeswing
    password: pass
##############################################################
# - 경로 : /src/main/resources 경로 하위
# - schema.sql : 테이블 생성 스크립트
# - data.sql : 데이터 입력 스크립트
# - 파일이름규칙 : schema-${platform}.sql , data-${platform}.sql
#   ex. schema-h2.sql , shcema-postgres.sql
#spring.datasource.initialization-mode=always # Spring Boot <v2.5.x
# DB초기화(schema.sql, data.sql) , [always : 기동 시 매번 동작, never : 기동 시 동작하지 않음]
  sql:
    init:
      schema-locations: classpath*:initdata/schema-postgresql.sql
      #data-locations: classpath*:initdata/data-postgresql.sql
      mode: always          # Spring Boot >=v2.5.0